"""initial schema

Revision ID: 44d4a1febf6a
Revises: 
Create Date: 2026-08-13 11:24:43.844419

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '44d4a1febf6a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('avatar_key', sa.String(length=64), nullable=False),
    sa.Column('caregiver_name', sa.String(length=120), nullable=False),
    sa.Column('contact_phone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_table('care_team_assignments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'patient_id', name='uq_care_team_patient')
    )
    op.create_index(op.f('ix_care_team_assignments_patient_id'), 'care_team_assignments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_team_assignments_user_id'), 'care_team_assignments', ['user_id'], unique=False)
    op.create_table('caregiver_patient_links',
    sa.Column('caregiver_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_kind', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caregiver_id', 'patient_id', name='uq_caregiver_patient')
    )
    op.create_index(op.f('ix_caregiver_patient_links_caregiver_id'), 'caregiver_patient_links', ['caregiver_id'], unique=False)
    op.create_index(op.f('ix_caregiver_patient_links_patient_id'), 'caregiver_patient_links', ['patient_id'], unique=False)
    op.create_table('feeling_check_ins',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('mood', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('operation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_feeling_check_ins_patient_id'), 'feeling_check_ins', ['patient_id'], unique=False)
    op.create_table('milestones',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('preparation', sa.Text(), nullable=True),
    sa.Column('service', sa.String(length=120), nullable=True),
    sa.Column('confirmation_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attendance_confirmed', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_patient_id'), 'milestones', ['patient_id'], unique=False)
    op.create_table('notification_outbox',
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index(op.f('ix_notification_outbox_recipient_id'), 'notification_outbox', ['recipient_id'], unique=False)
    op.create_table('processed_operations',
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('operation_type', sa.String(length=48), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_summary', sa.String(length=200), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_operations_operation_id'), 'processed_operations', ['operation_id'], unique=True)
    op.create_index(op.f('ix_processed_operations_user_id'), 'processed_operations', ['user_id'], unique=False)
    op.create_table('attendance_confirmations',
    sa.Column('milestone_id', sa.Uuid(), nullable=False),
    sa.Column('caregiver_id', sa.Uuid(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_attendance_confirmations_milestone_id'), 'attendance_confirmations', ['milestone_id'], unique=False)
    op.create_table('barrier_alerts',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reported_by', sa.Uuid(), nullable=True),
    sa.Column('first_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_contact_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('operation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['first_contact_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_barrier_alerts_milestone_id'), 'barrier_alerts', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_barrier_alerts_patient_id'), 'barrier_alerts', ['patient_id'], unique=False)
    op.create_table('interventions',
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=48), nullable=False),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Uuid(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['barrier_alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_interventions_alert_id'), 'interventions', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interventions_alert_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_barrier_alerts_patient_id'), table_name='barrier_alerts')
    op.drop_index(op.f('ix_barrier_alerts_milestone_id'), table_name='barrier_alerts')
    op.drop_table('barrier_alerts')
    op.drop_index(op.f('ix_attendance_confirmations_milestone_id'), table_name='attendance_confirmations')
    op.drop_table('attendance_confirmations')
    op.drop_index(op.f('ix_processed_operations_user_id'), table_name='processed_operations')
    op.drop_index(op.f('ix_processed_operations_operation_id'), table_name='processed_operations')
    op.drop_table('processed_operations')
    op.drop_index(op.f('ix_notification_outbox_recipient_id'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    op.drop_index(op.f('ix_milestones_patient_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_feeling_check_ins_patient_id'), table_name='feeling_check_ins')
    op.drop_table('feeling_check_ins')
    op.drop_index(op.f('ix_caregiver_patient_links_patient_id'), table_name='caregiver_patient_links')
    op.drop_index(op.f('ix_caregiver_patient_links_caregiver_id'), table_name='caregiver_patient_links')
    op.drop_table('caregiver_patient_links')
    op.drop_index(op.f('ix_care_team_assignments_user_id'), table_name='care_team_assignments')
    op.drop_index(op.f('ix_care_team_assignments_patient_id'), table_name='care_team_assignments')
    op.drop_table('care_team_assignments')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('patients')
    # ### end Alembic commands ###
