"""phase 4 companion patient identity

Revision ID: 8a5c70ba54d1
Revises: c442feb4e762
Create Date: 2026-08-14 11:02:04.743821

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '8a5c70ba54d1'
down_revision: str | None = 'c442feb4e762'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companion_preferences',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('chosen_name', sa.String(length=60), nullable=True),
    sa.Column('avatar_key', sa.String(length=40), nullable=True),
    sa.Column('comfort_object', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', name='uq_companion_prefs_patient')
    )
    op.create_index(op.f('ix_companion_preferences_patient_id'), 'companion_preferences', ['patient_id'], unique=False)
    op.create_table('patient_content_settings',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('development_band', sa.String(length=24), nullable=False),
    sa.Column('enabled_categories', sa.JSON(), nullable=True),
    sa.Column('show_immediate_preparation', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', name='uq_content_settings_patient')
    )
    op.create_index(op.f('ix_patient_content_settings_patient_id'), 'patient_content_settings', ['patient_id'], unique=False)
    op.create_table('patient_support_requests',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('request_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('operation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_patient_support_requests_patient_id'), 'patient_support_requests', ['patient_id'], unique=False)
    op.create_table('patient_user_links',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('activated_by', sa.Uuid(), nullable=True),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', name='uq_patient_link_patient'),
    sa.UniqueConstraint('user_id', name='uq_patient_link_user')
    )
    op.create_index(op.f('ix_patient_user_links_patient_id'), 'patient_user_links', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_user_links_user_id'), 'patient_user_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_user_links_user_id'), table_name='patient_user_links')
    op.drop_index(op.f('ix_patient_user_links_patient_id'), table_name='patient_user_links')
    op.drop_table('patient_user_links')
    op.drop_index(op.f('ix_patient_support_requests_patient_id'), table_name='patient_support_requests')
    op.drop_table('patient_support_requests')
    op.drop_index(op.f('ix_patient_content_settings_patient_id'), table_name='patient_content_settings')
    op.drop_table('patient_content_settings')
    op.drop_index(op.f('ix_companion_preferences_patient_id'), table_name='companion_preferences')
    op.drop_table('companion_preferences')
    # ### end Alembic commands ###
