"""phase 3 knowledge conversation pgvector

Revision ID: c442feb4e762
Revises: 8a7e3e41c911
Create Date: 2026-08-13 19:25:03.898593

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

revision: str = 'c442feb4e762'
down_revision: str | None = '8a7e3e41c911'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `autogenerate` no detecta extensiones: la columna `vector` no puede
    # crearse si la extensión no existe todavía, así que va primero.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('audience', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_slug'), 'knowledge_documents', ['slug'], unique=True)
    op.create_table('conversation_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_sessions_user_id'), 'conversation_sessions', ['user_id'], unique=False)
    op.create_table('knowledge_document_versions',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('storage_bucket', sa.String(length=120), nullable=False),
    sa.Column('storage_path', sa.String(length=400), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version', name='uq_document_version')
    )
    op.create_index(op.f('ix_knowledge_document_versions_checksum'), 'knowledge_document_versions', ['checksum'], unique=False)
    op.create_index(op.f('ix_knowledge_document_versions_document_id'), 'knowledge_document_versions', ['document_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(length=48), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('needs_human', sa.Boolean(), nullable=False),
    sa.Column('proposed_action', sa.JSON(), nullable=True),
    sa.Column('action_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operation_id', sa.Uuid(), nullable=True),
    sa.Column('resulting_operation_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=300), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedding_model', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_version_id'), 'knowledge_chunks', ['version_id'], unique=False)
    op.create_table('knowledge_ingestion_jobs',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('extractor', sa.String(length=120), nullable=True),
    sa.Column('embedding_model', sa.String(length=120), nullable=True),
    sa.Column('chunks_created', sa.Integer(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_ingestion_jobs_version_id'), 'knowledge_ingestion_jobs', ['version_id'], unique=False)
    op.create_table('ai_runs',
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('model_id', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('usage_units', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('safety_code', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runs_message_id'), 'ai_runs', ['message_id'], unique=False)
    op.create_table('conversation_media',
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('bucket', sa.String(length=120), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_media_message_id'), 'conversation_media', ['message_id'], unique=False)
    op.create_table('retrieval_evidence',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_evidence_message_id'), 'retrieval_evidence', ['message_id'], unique=False)
    op.create_table('safety_events',
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_events_session_id'), 'safety_events', ['session_id'], unique=False)
    # ### end Alembic commands ###

    # --- Búsqueda léxica -----------------------------------------------------
    # Columna generada: PostgreSQL la mantiene sincronizada con `content`. Hacerlo
    # en Python dejaría el índice a merced de que nadie olvide actualizarlo.
    op.execute(
        """
        ALTER TABLE knowledge_chunks
        ADD COLUMN content_tsv tsvector
        GENERATED ALWAYS AS (to_tsvector('spanish', coalesce(content, ''))) STORED
        """
    )
    op.execute(
        "CREATE INDEX ix_knowledge_chunks_content_tsv "
        "ON knowledge_chunks USING GIN (content_tsv)"
    )

    # --- Búsqueda semántica --------------------------------------------------
    # HNSW con distancia coseno, que es la métrica de los embeddings usados.
    # `m` y `ef_construction` conservadores: el corpus institucional del piloto
    # es pequeño y no justifica un índice caro de construir.
    op.execute(
        "CREATE INDEX ix_knowledge_chunks_embedding "
        "ON knowledge_chunks USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )

    # Filtro que precede a todo ranking: sólo versiones publicadas y vigentes.
    op.execute(
        "CREATE INDEX ix_knowledge_versions_published "
        "ON knowledge_document_versions (status, valid_from, valid_until)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_knowledge_versions_published")
    op.execute("DROP INDEX IF EXISTS ix_knowledge_chunks_embedding")
    op.execute("DROP INDEX IF EXISTS ix_knowledge_chunks_content_tsv")
    op.execute("ALTER TABLE knowledge_chunks DROP COLUMN IF EXISTS content_tsv")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_events_session_id'), table_name='safety_events')
    op.drop_table('safety_events')
    op.drop_index(op.f('ix_retrieval_evidence_message_id'), table_name='retrieval_evidence')
    op.drop_table('retrieval_evidence')
    op.drop_index(op.f('ix_conversation_media_message_id'), table_name='conversation_media')
    op.drop_table('conversation_media')
    op.drop_index(op.f('ix_ai_runs_message_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_knowledge_ingestion_jobs_version_id'), table_name='knowledge_ingestion_jobs')
    op.drop_table('knowledge_ingestion_jobs')
    op.drop_index(op.f('ix_knowledge_chunks_version_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_knowledge_document_versions_document_id'), table_name='knowledge_document_versions')
    op.drop_index(op.f('ix_knowledge_document_versions_checksum'), table_name='knowledge_document_versions')
    op.drop_table('knowledge_document_versions')
    op.drop_index(op.f('ix_conversation_sessions_user_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_knowledge_documents_slug'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
